import { DataResponse, postJson } from "../utils/httpHelpers";
import {
    CreateTeamInput,
    CreateTeamOutput,
    CreateWorkspaceInput,
    CreateWorkspaceOutput,
    FetchWorkspaceInput,
    FetchWorkspaceOutput
} from "./GiantTeam";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export const postCreateTeam = async (input: CreateTeamInput) =>
    await postJson("/api/create-team", input) as DataResponse<CreateTeamOutput>;

export const postCreateWorkspace = async (input: CreateWorkspaceInput) =>
    await postJson("/api/create-workspace", input) as DataResponse<CreateWorkspaceOutput>;

export const postFetchWorkspace = async (input: FetchWorkspaceInput) =>
    await postJson("/api/fetch-workspace", input) as DataResponse<FetchWorkspaceOutput>;