import {
    CreateTeamInput,
    CreateTeamOutput,
    CreateWorkspaceInput,
    CreateWorkspaceOutput,
    FetchWorkspaceInput,
    FetchWorkspaceOutput,
} from "./GiantTeam";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export const postCreateTeam = async (input: CreateTeamInput): Promise<CreateTeamOutput> => {
    const response = await fetch("/api/create-team", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(input)
    });
    return response.json();
}

export const postCreateWorkspace = async (input: CreateWorkspaceInput): Promise<CreateWorkspaceOutput> => {
    const response = await fetch("/api/create-workspace", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(input)
    });
    return response.json();
}

export const postFetchWorkspace = async (input: FetchWorkspaceInput): Promise<FetchWorkspaceOutput> => {
    const response = await fetch("/api/fetch-workspace", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(input)
    });
    return response.json();
}