// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface DbRole {
    roleId: string;
    created: Date;
}

export interface User {
    userId: string;
    name: string;
    username: string;
    invariantUsername: string;
    email: string;
    emailVerified: boolean;
    created: Date;
    dbRoleId: string;
    dbRole?: DbRole;
}

export interface CreateTeamInput {
    teamName?: string;
}

export interface CreateTeamOutput {
    teamId: string;
}

export interface JoinInput {
    name: string;
    email: string;
    username: string;
    password: string;
}

export interface JoinOutput {
    userId: string;
}

export interface SessionUser {
    userId: string;
    sub: string;
    username: string;
    dbRole: string;
    dbLogin: string;
    dbPassword: string;
}

export interface VerifyPasswordInput {
    username: string;
    password: string;
}

export interface VerifyPasswordOutput {
    userId: string;
}

export interface CreateWorkspaceInput {
    workspaceName?: string;
    workspaceOwner?: string;
}

export interface CreateWorkspaceOutput {
    workspaceName: string;
}

export interface DeleteWorkspaceInput {
    workspaceId?: string;
}

export interface DeleteWorkspaceOutput {
    status: DeleteWorkspaceStatus;
    message?: string;
}

export enum DeleteWorkspaceStatus {
    Success = 200,
    Problem = 400,
}

export interface FetchRoleInput {
    roleName?: string;
}

export interface FetchRoleMemberOutput {
    roleName: string;
    inherit: boolean;
    teamAdmin: boolean;
}

export interface FetchRoleOutput {
    roleName: string;
    canLogin: boolean;
    createDb: boolean;
    inherit: boolean;
    members: FetchRoleMemberOutput[];
}

export interface FetchWorkspaceInput {
    workspaceName?: string;
}

export interface FetchWorkspaceOutput {
    name: string;
    owner: string;
    schemas: FetchWorkspaceSchema[];
}

export interface FetchWorkspaceSchema {
    name: string;
    owner: string;
    tables: FetchWorkspaceTable[];
}

export interface FetchWorkspaceTable {
    name: string;
    owner: string;
}

export interface FetchRecords {
    sql?: string;
    columns: FetchRecordsColumn[];
    records: any[][];
}

export interface FetchRecordsColumn {
    name: string;
    dataType: string;
    nullable: boolean;
}

export interface FetchRecordsInput {
    verbose?: boolean;
    database: string;
    schema: string;
    table: string;
    columns?: FetchRecordsInputColumn[];
    filters?: FetchRecordsInputRangeFilter[];
    skip?: number;
    take?: number;
}

export interface FetchRecordsInputColumn {
    name: string;
    position?: number;
    sort: Sort;
    visible?: boolean;
}

export interface FetchRecordsInputFilter {
    discriminator: string;
    column: string;
}

export interface FetchRecordsInputOrder {
    column: string;
    desc?: boolean;
}

export interface FetchRecordsInputRangeFilter {
    lowerValue: string;
    upperValue: string;
    discriminator: string;
    column: string;
}

export interface ImportDataInput {
    database: string;
    schema?: string;
    table?: string;
    createTableIfNotExists?: boolean;
    data?: string;
}

export interface ImportDataOutput {
    schema: string;
    table: string;
}

export enum Sort {
    Unsorted = 0,
    Asc = 1,
    Desc = 2,
}