// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface FetchOrganizationProps {
    organizationId: string;
}

export interface OrganizationInfo {
    databaseName: string | null;
}

export interface SpaceInfo {
    schemaName: string | null;
}