// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface Column {
    position: number;
    name: string;
    storeType: string;
    isNullable: boolean;
    defaultValueSql: string | null;
    computedColumnSql: string | null;
}

export interface Database {
    defaultSchema: string | null;
    schemas: Schema[];
    scripts: string[];
}

export interface DefaultPrivileges {
    privileges: string;
    objectType: string;
    grantee: string;
}

export enum DefaultPrivilegesEnum {
    Tables = 0,
    Sequences = 1,
    Functions = 2,
    Types = 3,
}

export interface Schema {
    name: string;
    owner: string | null;
    tables: Table[];
    privileges: SchemaPrivileges[];
    defaultPrivileges: DefaultPrivileges[];
}

export interface SchemaPrivileges {
    grantee: string;
    privileges: string;
}

export const StoreType = {
    array: 'array',
    bigint: 'bigint',
    bigIntMultirange: 'bigintmultirange',
    bigIntRange: 'bigintrange',
    bit: 'bit',
    boolean: 'boolean',
    box: 'box',
    bytea: 'bytea',
    char: 'char',
    cid: 'cid',
    cidr: 'cidr',
    circle: 'circle',
    citext: 'citext',
    date: 'date',
    dateMultirange: 'datemultirange',
    dateRange: 'daterange',
    double: 'double',
    geography: 'geography',
    geometry: 'geometry',
    hstore: 'hstore',
    inet: 'inet',
    int2Vector: 'int2vector',
    integer: 'integer',
    integerMultirange: 'integermultirange',
    integerRange: 'integerrange',
    internalChar: 'internalchar',
    interval: 'interval',
    json: 'json',
    jsonb: 'jsonb',
    jsonPath: 'jsonpath',
    line: 'line',
    lQuery: 'lquery',
    lSeg: 'lseg',
    lTree: 'ltree',
    lTxtQuery: 'ltxtquery',
    macAddr: 'macaddr',
    macAddr8: 'macaddr8',
    money: 'money',
    multirange: 'multirange',
    name: 'name',
    numeric: 'numeric',
    numericMultirange: 'numericmultirange',
    numericRange: 'numericrange',
    oid: 'oid',
    oidvector: 'oidvector',
    path: 'path',
    pgLsn: 'pglsn',
    point: 'point',
    polygon: 'polygon',
    range: 'range',
    real: 'real',
    refcursor: 'refcursor',
    regconfig: 'regconfig',
    regtype: 'regtype',
    smallint: 'smallint',
    text: 'text',
    tid: 'tid',
    time: 'time',
    timestamp: 'timestamp',
    timestampMultirange: 'timestampmultirange',
    timestampRange: 'timestamprange',
    timestampTz: 'timestamptz',
    timestampTzMultirange: 'timestamptzmultirange',
    timestampTzRange: 'timestamptzrange',
    timeTz: 'timetz',
    tsQuery: 'tsquery',
    tsVector: 'tsvector',
    unknown: 'unknown',
    uuid: 'uuid',
    varbit: 'varbit',
    varchar: 'varchar',
    xid: 'xid',
    xid8: 'xid8',
    xml: 'xml',
}

export interface Table {
    name: string;
    owner: string | null;
    columns: Column[];
    indexes: TableIndex[];
}

export interface TableIndex {
    name: string | null;
    indexType: TableIndexType;
    columns: string[];
}

export enum TableIndexType {
    Index = 0,
    UniqueConstraint = 1,
    PrimaryKey = 2,
}