import { DataResponse, postJson } from "../utils/httpHelpers";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface LoginInput {
    username?: string;
    password?: string;
    remainLoggedIn: boolean;
}

export interface LoginOutput {
    status: LoginStatus;
    message?: string;
}

export enum LoginStatus {
    Success = 200,
    Problem = 400,
}

export interface RegisterInput {
    name: string;
    email: string;
    username: string;
    password: string;
    passwordConfirmation: string;
}

export interface RegisterOutput {
    status: RegisterStatus;
    message?: string;
    userId?: string;
}

export enum RegisterStatus {
    Success = 200,
    Problem = 400,
}

export interface SessionOutput {
    status: SessionStatus;
    userId?: string;
    username?: string;
    name?: string;
}

export enum SessionStatus {
    Anonymous = 0,
    Authenticated = 1,
}

export const postLogin = async (input: LoginInput): Promise<DataResponse<LoginOutput>> => 
    await postJson("/api/login", input);

export const postLogout = async () => 
    await postJson("/api/logout");

export const postRegister = async (input: RegisterInput): Promise<DataResponse<RegisterOutput>> => 
    await postJson("/api/register", input);

export const postSession = async (): Promise<DataResponse<SessionOutput>> => 
    await postJson("/api/session");