import { DataResponse, postJson } from "../utils/httpHelpers";
import { JoinInput, JoinOutput } from "./GiantTeam";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface LoginInput {
    username?: string;
    password?: string;
    remainLoggedIn: boolean;
}

export interface SessionOutput {
    status: SessionStatus;
    userId?: string;
    username?: string;
}

export enum SessionStatus {
    Anonymous = 0,
    Authenticated = 1,
}

export const postLogin = async (input: LoginInput) =>
    await postJson("/api/login", input) as DataResponse<null>;

export const postLogout = async () =>
    await postJson("/api/logout") as DataResponse<null>;

export const postRegister = async (input: JoinInput) =>
    await postJson("/api/register", input) as DataResponse<JoinOutput>;

export const postSession = async () =>
    await postJson("/api/session") as DataResponse<SessionOutput>;