import { DataResponse, postJson } from '../helpers/httpHelpers';
import {
    CreateTable,
    CreateTableInput,
    CreateTeamInput,
    CreateTeamOutput,
    CreateWorkspaceInput,
    CreateWorkspaceOutput,
    FetchRecords,
    FetchRecordsInput,
    FetchWorkspaceInput,
    FetchWorkspaceOutput,
    ImportDataInput,
    ImportDataOutput
} from './GiantTeam';

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export const postCreateTable = async (input: CreateTableInput) =>
    await postJson('/api/create-table', input) as DataResponse<CreateTable>;

export const postCreateTeam = async (input: CreateTeamInput) =>
    await postJson('/api/create-team', input) as DataResponse<CreateTeamOutput>;

export const postCreateWorkspace = async (input: CreateWorkspaceInput) =>
    await postJson('/api/create-workspace', input) as DataResponse<CreateWorkspaceOutput>;

export const postFetchRecords = async (input: FetchRecordsInput) =>
    await postJson('/api/fetch-records', input) as DataResponse<FetchRecords>;

export const postFetchWorkspace = async (input: FetchWorkspaceInput) =>
    await postJson('/api/fetch-workspace', input) as DataResponse<FetchWorkspaceOutput>;

export const postImportData = async (input: ImportDataInput) =>
    await postJson('/api/import-data', input) as DataResponse<ImportDataOutput>;