// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface CreateOrganizationProps {
    name: string;
    databaseName: string;
}

export interface CreateOrganizationResult {
    organizationId: string;
}