import { Schema } from "./GiantTeam.DatabaseDefinition.Models";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface Workspace {
    name: string;
    owner: string;
    zones: Schema[];
}