// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface DbRole {
    roleId: string;
    created: Date;
}

export interface User {
    userId: string;
    name: string;
    username: string;
    invariantUsername: string;
    email: string;
    emailVerified: boolean;
    created: Date;
    dbRoleId: string;
    dbRole?: DbRole;
}

export interface CreateTeamInput {
    teamName?: string;
}

export interface CreateTeamOutput {
    teamId?: string;
}

export interface JoinInput {
    name: string;
    email: string;
    username: string;
    password: string;
}

export interface JoinOutput {
    userId: string;
}

export interface VerifyPasswordInput {
    username: string;
    password: string;
}

export interface VerifyPasswordOutput {
    status: VerifyPasswordStatus;
    message?: string;
    userId?: string;
}

export enum VerifyPasswordStatus {
    Success = 200,
    Problem = 400,
}

export interface CreateWorkspaceInput {
    workspaceName?: string;
    workspaceOwner?: string;
}

export interface CreateWorkspaceOutput {
    status: CreateWorkspaceStatus;
    message?: string;
    workspaceName?: string;
}

export enum CreateWorkspaceStatus {
    Success = 200,
    Problem = 400,
}

export interface DeleteWorkspaceInput {
    workspaceId?: string;
}

export interface DeleteWorkspaceOutput {
    status: DeleteWorkspaceStatus;
    message?: string;
}

export enum DeleteWorkspaceStatus {
    Success = 200,
    Problem = 400,
}

export interface FetchRoleInput {
    roleName?: string;
}

export interface FetchRoleMemberOutput {
    roleName: string;
    inherit: boolean;
    teamAdmin: boolean;
}

export interface FetchRoleOutput {
    roleName: string;
    canLogin: boolean;
    createDb: boolean;
    inherit: boolean;
    members: FetchRoleMemberOutput[];
}

export interface FetchWorkspaceInput {
    workspaceName?: string;
}

export interface FetchWorkspaceOutput {
    workspaceName: string;
    workspaceOwner: string;
}