// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface CreateWorkspaceRoleInput {
    workspaceName: string | null;
    roleName: string | null;
}

export interface CreateWorkspaceRoleOutput {
}

export interface JoinInput {
    name: string;
    email: string;
    username: string;
    password: string;
}

export interface JoinOutput {
    userId: string;
}

export interface SessionUser {
    userId: string;
    sub: string;
    username: string;
    dbUser: string;
    dbLogin: string;
    dbPassword: string;
    dbRegular: string;
    dbElevated: string;
}

export interface VerifyPasswordInput {
    username: string;
    password: string;
}

export interface VerifyPasswordOutput {
    userId: string;
}