// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface CreateWorkspaceInput {
    workspaceName: string | null;
    isPublic: boolean;
}

export interface CreateWorkspaceOutput {
}

export interface DeleteWorkspaceInput {
    workspaceId: string | null;
}

export interface DeleteWorkspaceOutput {
    status: DeleteWorkspaceStatus;
    message: string | null;
}

export enum DeleteWorkspaceStatus {
    Success = 200,
    Problem = 400,
}

export interface FetchRoleInput {
    roleName: string | null;
}

export interface FetchRoleMemberOutput {
    roleName: string;
    inherit: boolean;
    teamAdmin: boolean;
}

export interface FetchRoleOutput {
    roleName: string;
    canLogin: boolean;
    createDb: boolean;
    inherit: boolean;
    members: FetchRoleMemberOutput[];
}