import { DatabaseAlteration } from "./GiantTeam.DatabaseDefinition.Alterations.Models";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface AlterDatabaseInput {
    databaseName: string;
    changes: DatabaseAlteration[];
}

export interface AlterDatabaseOutput {
}