import { postJson, DataResponse } from "../helpers/httpHelpers";
import { QueryDatabaseInput } from "./GiantTeam.Databases.Database.Services";
import { AlterDatabaseInput, AlterDatabaseOutput } from "./GiantTeam.Organizations.Organization.Database.Services";
import { CreateSpaceInput, CreateSpaceResult } from "./GiantTeam.Organizations.Organization.Services";
import { QueryTable } from "./GiantTeam.Postgres.Models";
import { FetchRecordsInput, FetchRecords, ImportDataInput, ImportDataOutput } from "./GiantTeam.Workspaces.Services";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export const postAlterDatabase = async (input: AlterDatabaseInput) =>
    await postJson('/api/organization/alter-database', input) as DataResponse<AlterDatabaseOutput>;

export const postCreateSpace = async (input: CreateSpaceInput) =>
    await postJson('/api/organization/create-space', input) as DataResponse<CreateSpaceResult>;

export const postFetchRecords = async (input: FetchRecordsInput) =>
    await postJson('/api/organization/fetch-records', input) as DataResponse<FetchRecords>;

export const postImportData = async (input: ImportDataInput) =>
    await postJson('/api/organization/import-data', input) as DataResponse<ImportDataOutput>;

export const postQueryDatabase = async (input: QueryDatabaseInput) =>
    await postJson('/api/organization/query-database', input) as DataResponse<QueryTable>;