// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface CreateOrganizationInput {
    name: string;
    databaseName: string;
}

export interface CreateOrganizationResult {
    organizationId: string;
}

export interface FetchOrganizationInput {
    organizationId: string;
}

export interface FetchOrganizationOutput {
    organizationId: string;
    name: string;
    databaseName: string;
    created: Date;
}