import { postJson, DataResponse } from "../helpers/httpHelpers";
import { CreateOrganizationInput, CreateOrganizationResult, FetchOrganizationInput, FetchOrganizationOutput } from "./GiantTeam.Cluster.Directory.Services";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export const postCreateOrganization = async (input: CreateOrganizationInput) =>
    await postJson('/api/cluster/create-organization', input) as DataResponse<CreateOrganizationResult>;

export const postFetchOrganization = async (input: FetchOrganizationInput) =>
    await postJson('/api/cluster/fetch-organization', input) as DataResponse<FetchOrganizationOutput>;