// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface JoinInput {
    name: string;
    email: string;
    username: string;
    password: string;
}

export interface JoinOutput {
    userId: string;
}

export interface SessionUser {
    userId: string;
    sub: string;
    username: string;
    elevated: boolean;
    dbUser: string;
    dbLogin: string;
    dbPassword: string;
    dbElevatedUser: string | null;
    dbElevatedLogin: string | null;
}

export interface VerifyPasswordInput {
    username: string;
    password: string;
}

export interface VerifyPasswordOutput {
    userId: string;
}