import { DatabaseAlteration } from "./GiantTeam.DatabaseDefinition.Alterations.Models";
import { Inode } from "./GiantTeam.Organization.Etc.Models";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface AlterDatabaseInput {
    databaseName: string;
    changes: DatabaseAlteration[];
}

export interface AlterDatabaseOutput {
}

export interface CreateSpaceInput {
    organizationId: string;
    spaceName: string;
    grants: GrantSpaceInputGrant[];
}

export interface CreateSpaceResult {
    inodeId: string;
}

export interface FetchInodeInput {
    organizationId: string;
    path: string;
}

export interface FetchInodeResult {
    inode: Inode;
}

export interface FetchOrganizationDetailsApp {
    appId: string;
    name: string;
    inodeTypeIds: string[];
}

export interface FetchOrganizationDetailsInput {
    organizationId: string;
}

export interface FetchOrganizationDetailsResult {
    organizationId: string;
    name: string;
    databaseName: string;
    created: Date;
    apps: FetchOrganizationDetailsApp[];
    roles: FetchOrganizationDetailsRole[];
    inode: Inode;
}

export interface FetchOrganizationDetailsRole {
    name: string;
    dbRole: string;
}

export interface FetchRecords {
    sql: string | null;
    columns: FetchRecordsColumn[];
    records: any[][];
}

export interface FetchRecordsColumn {
    name: string;
    dataType: string;
    nullable: boolean;
}

export interface FetchRecordsInput {
    verbose: boolean | null;
    database: string;
    schema: string;
    table: string;
    columns: FetchRecordsInputColumn[] | null;
    filters: FetchRecordsInputRangeFilter[] | null;
    skip: number | null;
    take: number | null;
}

export interface FetchRecordsInputColumn {
    name: string;
    position: number | null;
    sort: Sort;
    visible: boolean | null;
}

export interface FetchRecordsInputFilter {
    $type: string;
    column: string;
}

export interface FetchRecordsInputOrder {
    column: string;
    desc: boolean | null;
}

export interface FetchRecordsInputRangeFilter extends FetchRecordsInputFilter {
    $type: 'FetchRecordsInputRangeFilter';
    lowerValue: string;
    upperValue: string;
    column: string;
}

export interface GrantSpaceInput {
    organizationId: string;
    spaceName: string;
    grants: GrantSpaceInputGrant[];
}

export interface GrantSpaceInputGrant {
    organizationRoleId: string;
    privileges: GrantSpaceInputPrivilege[];
}

export enum GrantSpaceInputPrivilege {
    USAGE = 0,
    CREATE = 1,
    ALL = 100,
}

export interface GrantSpaceResult {
}

export interface GrantTableInput {
    organizationId: string;
    spaceName: string;
    tableName: string;
    grants: GrantTableInputGrant[];
}

export interface GrantTableInputGrant {
    organizationRoleId: string;
    privileges: GrantTableInputPrivilege[];
}

export enum GrantTableInputPrivilege {
    SELECT = 0,
    INSERT = 1,
    UPDATE = 2,
    DELETE = 3,
    TRUNCATE = 4,
    REFERENCES = 5,
    TRIGGER = 6,
    ALL = 100,
}

export interface GrantTableResult {
}

export interface ImportDataInput {
    database: string;
    schema: string | null;
    table: string | null;
    createTableIfNotExists: boolean | null;
    data: string | null;
}

export interface ImportDataOutput {
    schema: string;
    table: string;
}

export interface QueryDatabaseInput {
    databaseName: string;
    sql: string;
}

export enum Sort {
    Unsorted = 0,
    Asc = 1,
    Desc = 2,
}