// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface CreateSpaceInput {
    databaseName: string;
    name: string;
    schemaName: string;
}

export interface CreateSpaceResult {
    spaceId: string;
}