import { Schema } from "./GiantTeam.DatabaseDefinition.Models";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface Database {
    schemas: Schema[];
}

export interface Organization {
    id: string;
    database: Database;
}