// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface ObjectStatus {
    status: number;
    statusText: string;
    message: string;
    details: ObjectStatusDetail[];
}

export interface ObjectStatusDetail {
    message: string;
    members: string[];
}