// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface File {
    inode: Inode;
    contentType: string;
    data: string;
}

export interface Inode {
    inodeTypeId: string;
    inodeId: string;
    parentInodeId: string;
    name: string;
    created: Date;
    path: string;
    children: Inode[] | null;
}

export const InodeId = {
}

export interface InodeType {
    inodeTypeId: string;
    constraints: InodeTypeConstraint[];
}

export interface InodeTypeConstraint {
    parentInodeTypeId: string;
}

export interface Space {
    inode: Inode;
}