import { DatabaseAlteration } from "./GiantTeam.DatabaseDefinition.Alterations.Models";
import { InodeAccess } from "./GiantTeam.Organization.Etc.Models";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface AlterDatabaseInput {
    organizationId: string;
    changes: DatabaseAlteration[];
}

export interface AlterDatabaseOutput {
}

export interface CreateFolderInput {
    organizationId: string;
    parentInodeId: string;
    folderName: string;
    access: InodeAccess[];
}

export interface CreateSpaceInput {
    organizationId: string;
    spaceName: string;
    accessControlList: InodeAccess[];
}

export interface CreateTableInput {
    organizationId: string;
    parentInodeId: string;
    tableName: string;
    accessControlList: InodeAccess[];
}

export interface FetchInodeByPathInput {
    organizationId: string;
    path: string;
}

export interface FetchInodeChildrenInput {
    organizationId: string;
    parentInodeId: string;
}

export interface FetchInodeInput {
    organizationId: string;
    inodeId: string;
}

export interface FetchInodeListInput {
    organizationId: string;
    path: string;
}

export interface FetchOrganizationDetailsInput {
    organizationId: string;
}

export interface FetchRecords {
    sql: string | null;
    columns: FetchRecordsColumn[];
    records: any[][];
}

export interface FetchRecordsColumn {
    name: string;
    dataType: string;
    nullable: boolean;
}

export interface FetchRecordsInput {
    verbose: boolean | null;
    organizationId: string;
    schema: string;
    table: string;
    columns: FetchRecordsInputColumn[] | null;
    filters: FetchRecordsInputRangeFilter[] | null;
    skip: number | null;
    take: number | null;
}

export interface FetchRecordsInputColumn {
    name: string;
    position: number | null;
    sort: Sort;
    visible: boolean | null;
}

export interface FetchRecordsInputFilter {
    $type: string;
    column: string;
}

export interface FetchRecordsInputOrder {
    column: string;
    desc: boolean | null;
}

export interface FetchRecordsInputRangeFilter extends FetchRecordsInputFilter {
    $type: 'FetchRecordsInputRangeFilter';
    lowerValue: string;
    upperValue: string;
    column: string;
}

export interface FetchRolesInput {
    organizationId: string;
}

export interface GrantSpaceInput {
    organizationId: string;
    inodeId: string;
    accessControlList: InodeAccess[];
}

export interface GrantTableInput {
    organizationId: string;
    tableInodeId: string;
    accessControlList: InodeAccess[];
}

export interface ImportDataInput {
    organizationId: string;
    schema: string | null;
    table: string | null;
    createTableIfNotExists: boolean | null;
    data: string | null;
}

export interface ImportDataOutput {
    schema: string;
    table: string;
}

export interface QueryInput {
    organizationId: string;
    sql: string;
}

export enum Sort {
    Unsorted = 0,
    Asc = 1,
    Desc = 2,
}