// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface Column {
    position: number;
    name: string;
    storeType: string;
    isNullable: boolean;
    defaultValueSql: string | null;
    computedColumnSql: string | null;
}

export interface Database {
    defaultSchema: string | null;
    schemas: Schema[];
    scripts: string[];
}

export interface DefaultPrivileges {
    privileges: string;
    objectType: string;
    grantee: string;
}

export enum DefaultPrivilegesEnum {
    Tables = 0,
    Sequences = 1,
    Functions = 2,
    Types = 3,
}

export interface Schema {
    name: string;
    owner: string | null;
    tables: Table[];
    privileges: SchemaPrivileges[];
    defaultPrivileges: DefaultPrivileges[];
}

export interface SchemaPrivileges {
    grantee: string;
    privileges: string;
}

export enum StoreType {
    Array = 'array',
    Bigint = 'bigint',
    BigIntMultirange = 'bigintmultirange',
    BigIntRange = 'bigintrange',
    Bit = 'bit',
    Boolean = 'boolean',
    Box = 'box',
    Bytea = 'bytea',
    Char = 'char',
    Cid = 'cid',
    Cidr = 'cidr',
    Circle = 'circle',
    Citext = 'citext',
    Date = 'date',
    DateMultirange = 'datemultirange',
    DateRange = 'daterange',
    Double = 'double',
    Geography = 'geography',
    Geometry = 'geometry',
    Hstore = 'hstore',
    Inet = 'inet',
    Int2Vector = 'int2vector',
    Integer = 'integer',
    IntegerMultirange = 'integermultirange',
    IntegerRange = 'integerrange',
    InternalChar = 'internalchar',
    Interval = 'interval',
    Json = 'json',
    Jsonb = 'jsonb',
    JsonPath = 'jsonpath',
    Line = 'line',
    LQuery = 'lquery',
    LSeg = 'lseg',
    LTree = 'ltree',
    LTxtQuery = 'ltxtquery',
    MacAddr = 'macaddr',
    MacAddr8 = 'macaddr8',
    Money = 'money',
    Multirange = 'multirange',
    Name = 'name',
    Numeric = 'numeric',
    NumericMultirange = 'numericmultirange',
    NumericRange = 'numericrange',
    Oid = 'oid',
    Oidvector = 'oidvector',
    Path = 'path',
    PgLsn = 'pglsn',
    Point = 'point',
    Polygon = 'polygon',
    Range = 'range',
    Real = 'real',
    Refcursor = 'refcursor',
    Regconfig = 'regconfig',
    Regtype = 'regtype',
    Smallint = 'smallint',
    Text = 'text',
    Tid = 'tid',
    Time = 'time',
    Timestamp = 'timestamp',
    TimestampMultirange = 'timestampmultirange',
    TimestampRange = 'timestamprange',
    TimestampTz = 'timestamptz',
    TimestampTzMultirange = 'timestamptzmultirange',
    TimestampTzRange = 'timestamptzrange',
    TimeTz = 'timetz',
    TsQuery = 'tsquery',
    TsVector = 'tsvector',
    Unknown = 'unknown',
    Uuid = 'uuid',
    Varbit = 'varbit',
    Varchar = 'varchar',
    Xid = 'xid',
    Xid8 = 'xid8',
    Xml = 'xml',
}

export interface Table {
    name: string;
    owner: string | null;
    columns: Column[];
    indexes: TableIndex[];
}

export interface TableIndex {
    name: string | null;
    indexType: TableIndexType;
    columns: string[];
}

export enum TableIndexType {
    Index = 0,
    UniqueConstraint = 1,
    PrimaryKey = 2,
}