// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface File {
    node: Node;
    contentType: string;
    data: string;
}

export interface Node {
    typeId: string;
    nodeId: string;
    parentId: string;
    name: string;
    created: Date;
    path: string;
    children: Node[] | null;
}

export const NodeId = {
}

export interface NodeType {
    typeId: string;
    constraints: NodeTypeConstraint[];
}

export interface NodeTypeConstraint {
    parentTypeId: string;
}

export interface Space {
    node: Node;
}