import { postJson, DataResponse } from "../helpers/httpHelpers";
import { AlterDatabaseInput, AlterDatabaseOutput, CreateSpaceInput, CreateSpaceResult, FetchRecordsInput, FetchRecords, ImportDataInput, ImportDataOutput, QueryDatabaseInput, ExploreInput, ExploreResult, FetchOrganizationDetailsInput, FetchOrganizationDetailsResult } from "./GiantTeam.Organization.Services";
import { QueryTable } from "./GiantTeam.Postgres.Models";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export const postAlterDatabase = async (input: AlterDatabaseInput) =>
    await postJson('/api/organization/alter-database', input) as DataResponse<AlterDatabaseOutput>;

export const postCreateSpace = async (input: CreateSpaceInput) =>
    await postJson('/api/organization/create-space', input) as DataResponse<CreateSpaceResult>;

export const postExplore = async (input: ExploreInput) =>
    await postJson('/api/organization/explore', input) as DataResponse<ExploreResult>;

export const postFetchOrganizationDetails = async (input: FetchOrganizationDetailsInput) =>
    await postJson('/api/organization/fetch-organization-details', input) as DataResponse<FetchOrganizationDetailsResult>;

export const postFetchRecords = async (input: FetchRecordsInput) =>
    await postJson('/api/organization/fetch-records', input) as DataResponse<FetchRecords>;

export const postImportData = async (input: ImportDataInput) =>
    await postJson('/api/organization/import-data', input) as DataResponse<ImportDataOutput>;

export const postQueryDatabase = async (input: QueryDatabaseInput) =>
    await postJson('/api/organization/query-database', input) as DataResponse<QueryTable>;