import { postJson, DataResponse } from "../helpers/httpHelpers";
import { CreateOrganizationInput, CreateOrganizationResult, FetchOrganizationsOutput, QueryDirectoryInput } from "./GiantTeam.Cluster.Directory.Services";
import { TabularData } from "./GiantTeam.Postgres.Models";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export const postCreateOrganization = async (input: CreateOrganizationInput) =>
    await postJson('/api/cluster/create-organization', input) as DataResponse<CreateOrganizationResult>;

export const postFetchOrganizations = async () =>
    await postJson('/api/cluster/fetch-organizations') as DataResponse<FetchOrganizationsOutput>;

export const postQueryDirectory = async (input: QueryDirectoryInput) =>
    await postJson('/api/cluster/query-directory', input) as DataResponse<TabularData>;