import { Column, TableIndex } from "./GiantTeam.DatabaseDefinition.Models";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface AlterColumn extends DatabaseChange {
    $type: 'AlterColumn';
    schemaName: string;
    tableName: string;
    column: Column;
    modifications: AlterColumnModification[];
}

export enum AlterColumnModification {
    Nullability = 0,
    Default = 1,
    Type = 2,
    Generated = 3,
}

export interface AlterIndex extends DatabaseChange {
    $type: 'AlterIndex';
    schemaName: string;
    tableName: string;
    index: TableIndex;
}

export interface ChangeTableOwner extends DatabaseChange {
    $type: 'ChangeTableOwner';
    schemaName: string;
    tableName: string;
    newOwner: string;
}

export interface CreateColumn extends DatabaseChange {
    $type: 'CreateColumn';
    schemaName: string;
    tableName: string;
    column: Column;
}

export interface CreateIndex extends DatabaseChange {
    $type: 'CreateIndex';
    schemaName: string;
    tableName: string;
    index: TableIndex;
}

export interface CreateSchema extends DatabaseChange {
    $type: 'CreateSchema';
    schemaName: string;
}

export interface CreateTable extends DatabaseChange {
    $type: 'CreateTable';
    schemaName: string;
    tableName: string;
    columns: Column[];
}

export interface DatabaseChange {
    $type: string;
}

export interface DropColumn extends DatabaseChange {
    $type: 'DropColumn';
    schemaName: string;
    tableName: string;
    columnName: string;
}

export interface DropIndex extends DatabaseChange {
    $type: 'DropIndex';
    schemaName: string;
    tableName: string;
    index: TableIndex;
}

export interface RenameColumn extends DatabaseChange {
    $type: 'RenameColumn';
    schemaName: string;
    tableName: string;
    columnName: string;
    newColumnName: string;
}

export interface RenameTable extends DatabaseChange {
    $type: 'RenameTable';
    schemaName: string;
    tableName: string;
    newTableName: string;
}