import { postJson, DataResponse } from "../helpers/httpHelpers";
import { FetchOrganizationInput, FetchOrganizationOutput } from "./GiantTeam.Organizations.Directory.Services";
import { CreateOrganizationInput, CreateOrganizationResult } from "./GiantTeam.Organizations.Services";
import { CreateWorkspaceRoleInput, CreateWorkspaceRoleOutput } from "./GiantTeam.UserManagement.Services";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export const postCreateOrganization = async (input: CreateOrganizationInput) =>
    await postJson('/api/cluster/create-organization', input) as DataResponse<CreateOrganizationResult>;

export const postCreateWorkspaceRole = async (input: CreateWorkspaceRoleInput) =>
    await postJson('/api/cluster/create-workspace-role', input) as DataResponse<CreateWorkspaceRoleOutput>;

export const postFetchOrganization = async (input: FetchOrganizationInput) =>
    await postJson('/api/cluster/fetch-organization', input) as DataResponse<FetchOrganizationOutput>;