import { Icon } from '@iconify-icon/solid';
import add from '@iconify-icons/fluent/add-circle-20-filled';
import addOutline from '@iconify-icons/fluent/add-circle-20-regular';
import alert from '@iconify-icons/fluent/alert-12-filled';
import alertOutline from '@iconify-icons/fluent/alert-12-regular';
import apps from '@iconify-icons/fluent/apps-16-filled';
import appsOutline from '@iconify-icons/fluent/apps-16-regular';
import arrowDownCircle from '@iconify-icons/fluent/arrow-circle-down-12-filled';
import arrowDownCircleOutline from '@iconify-icons/fluent/arrow-circle-down-12-regular';
import arrowUpCircle from '@iconify-icons/fluent/arrow-circle-up-12-filled';
import arrowUpCircleOutline from '@iconify-icons/fluent/arrow-circle-up-12-regular';
import beakerFilled from '@iconify-icons/fluent/beaker-16-filled';
import beakerOutline from '@iconify-icons/fluent/beaker-16-regular';
import building from '@iconify-icons/fluent/building-multiple-20-filled';
import buildingOutline from '@iconify-icons/fluent/building-multiple-20-regular';
import caretDown from '@iconify-icons/fluent/caret-down-24-filled';
import caretRight from '@iconify-icons/fluent/caret-right-24-filled';
import chevronDown from '@iconify-icons/fluent/chevron-down-12-filled';
import columnEditFilled from '@iconify-icons/fluent/column-edit-20-filled';
import columnEditOutline from '@iconify-icons/fluent/column-edit-20-regular';
import deleteFilled from '@iconify-icons/fluent/delete-12-filled';
import deleteOutline from '@iconify-icons/fluent/delete-12-regular';
import dismiss from '@iconify-icons/fluent/dismiss-circle-20-filled';
import dismissOutline from '@iconify-icons/fluent/dismiss-circle-20-regular';
import editFilled from '@iconify-icons/fluent/edit-16-filled';
import editOutline from '@iconify-icons/fluent/edit-16-regular';
import eye from '@iconify-icons/fluent/eye-12-filled';
import eyeOff from '@iconify-icons/fluent/eye-off-16-filled';
import filter from '@iconify-icons/fluent/filter-20-filled';
import filterAdd from '@iconify-icons/fluent/filter-add-20-filled';
import home from '@iconify-icons/fluent/home-12-filled';
import homeOutline from '@iconify-icons/fluent/home-12-regular';
import informationCircle from '@iconify-icons/fluent/info-12-regular';
import left from '@iconify-icons/fluent/arrow-left-12-filled';
import menu from '@iconify-icons/fluent/navigation-16-filled';
import menuOutline from '@iconify-icons/fluent/navigation-16-regular';
import move from '@iconify-icons/fluent/arrow-move-20-filled';
import person from '@iconify-icons/fluent/person-12-filled';
import personOutline from '@iconify-icons/fluent/person-12-regular';
import presenceOffline10Regular from '@iconify-icons/fluent/presence-offline-10-regular';
import right from '@iconify-icons/fluent/arrow-right-12-filled';
import saveEditFilled from '@iconify-icons/fluent/save-edit-20-filled';
import search from '@iconify-icons/fluent/search-12-regular';
import sortAsc from '@iconify-icons/fluent/text-sort-ascending-16-regular';
import sortDesc from '@iconify-icons/fluent/text-sort-descending-16-regular';
import sparkles from '@iconify-icons/fluent/sparkle-16-filled';
import sparklesOutline from '@iconify-icons/fluent/sparkle-16-regular';
import spinner from '@iconify-icons/fluent/arrow-clockwise-12-filled';
import warning from '@iconify-icons/fluent/warning-12-regular';

export const AddIcon = (props: any) => <Icon icon={add} aria-hidden {...props} />;
export const AddOutlineIcon = (props: any) => <Icon icon={addOutline} aria-hidden {...props} />;
export const AlertIcon = (props: any) => <Icon icon={alert} aria-hidden {...props} />;
export const AlertOutlineIcon = (props: any) => <Icon icon={alertOutline} aria-hidden {...props} />;
export const AppsIcon = (props: any) => <Icon icon={apps} aria-hidden {...props} />;
export const AppsOutlineIcon = (props: any) => <Icon icon={appsOutline} aria-hidden {...props} />;
export const ArrowDownCircleIcon = (props: any) => <Icon icon={arrowDownCircle} aria-hidden {...props} />;
export const ArrowDownCircleOutlineIcon = (props: any) => <Icon icon={arrowDownCircleOutline} aria-hidden {...props} />;
export const ArrowUpCircleIcon = (props: any) => <Icon icon={arrowUpCircle} aria-hidden {...props} />;
export const ArrowUpCircleOutlineIcon = (props: any) => <Icon icon={arrowUpCircleOutline} aria-hidden {...props} />;
export const BeakerFilledIcon = (props: any) => <Icon icon={beakerFilled} aria-hidden {...props} />;
export const BeakerOutlineIcon = (props: any) => <Icon icon={beakerOutline} aria-hidden {...props} />;
export const BuildingIcon = (props: any) => <Icon icon={building} aria-hidden {...props} />;
export const BuildingOutlineIcon = (props: any) => <Icon icon={buildingOutline} aria-hidden {...props} />;
export const CaretDownIcon = (props: any) => <Icon icon={caretDown} aria-hidden {...props} />;
export const CaretRightIcon = (props: any) => <Icon icon={caretRight} aria-hidden {...props} />;
export const ChevronDownIcon = (props: any) => <Icon icon={chevronDown} aria-hidden {...props} />;
export const ColumnEditFilledIcon = (props: any) => <Icon icon={columnEditFilled} aria-hidden {...props} />;
export const ColumnEditOutlineIcon = (props: any) => <Icon icon={columnEditOutline} aria-hidden {...props} />;
export const DeleteFilledIcon = (props: any) => <Icon icon={deleteFilled} aria-hidden {...props} />;
export const DeleteOutlineIcon = (props: any) => <Icon icon={deleteOutline} aria-hidden {...props} />;
export const DismissIcon = (props: any) => <Icon icon={dismiss} aria-hidden {...props} />;
export const DismissOutlineIcon = (props: any) => <Icon icon={dismissOutline} aria-hidden {...props} />;
export const EditFilledIcon = (props: any) => <Icon icon={editFilled} aria-hidden {...props} />;
export const EditOutlineIcon = (props: any) => <Icon icon={editOutline} aria-hidden {...props} />;
export const EyeIcon = (props: any) => <Icon icon={eye} aria-hidden {...props} />;
export const EyeOffIcon = (props: any) => <Icon icon={eyeOff} aria-hidden {...props} />;
export const FilterAddIcon = (props: any) => <Icon icon={filterAdd} aria-hidden {...props} />;
export const FilterIcon = (props: any) => <Icon icon={filter} aria-hidden {...props} />;
export const HomeIcon = (props: any) => <Icon icon={home} aria-hidden {...props} />;
export const HomeOutlineIcon = (props: any) => <Icon icon={homeOutline} aria-hidden {...props} />;
export const InfoIcon = (props: any) => <Icon icon={informationCircle} aria-hidden {...props} />;
export const LeftIcon = (props: any) => <Icon icon={left} aria-hidden {...props} />;
export const MenuIcon = (props: any) => <Icon icon={menu} aria-hidden {...props} />;
export const MenuOutline = (props: any) => <Icon icon={menuOutline} aria-hidden {...props} />;
export const MoveIcon = (props: any) => <Icon icon={move} aria-hidden {...props} />;
export const OffIcon = (props: any) => <Icon icon={presenceOffline10Regular} aria-hidden {...props} />;
export const PersonIcon = (props: any) => <Icon icon={person} aria-hidden {...props} />;
export const PersonOutlineIcon = (props: any) => <Icon icon={personOutline} aria-hidden {...props} />;
export const RightIcon = (props: any) => <Icon icon={right} aria-hidden {...props} />;
export const SaveEditFilledIcon = (props: any) => <Icon icon={saveEditFilled} aria-hidden {...props} />;
export const SearchIcon = (props: any) => <Icon icon={search} aria-hidden {...props} />;
export const SortAscIcon = (props: any) => <Icon icon={sortAsc} aria-hidden {...props} />;
export const SortDescIcon = (props: any) => <Icon icon={sortDesc} aria-hidden {...props} />;
export const SparklesIcon = (props: any) => <Icon icon={sparkles} aria-hidden {...props} />;
export const SparklesOutlineIcon = (props: any) => <Icon icon={sparklesOutline} aria-hidden {...props} />;
export const SpinnerIcon = (props: any) => <Icon icon={spinner} aria-hidden {...props} />;
export const WarningIcon = (props: any) => <Icon icon={warning} aria-hidden {...props} />;