import { Icon } from '@iconify-icon/solid';
import chevronDown from '@iconify-icons/ion/chevron-down';
import home from '@iconify-icons/ion/home';
import homeOutline from '@iconify-icons/ion/home-outline';
import informationCircle from '@iconify-icons/ion/information-circle';
import menu from '@iconify-icons/ion/menu';
import menuOutline from '@iconify-icons/ion/menu-outline';
import notificationsOutline from '@iconify-icons/ion/notifications-outline';
import person from '@iconify-icons/ion/person';
import personOutline from '@iconify-icons/ion/person-outline';
import search from '@iconify-icons/ion/search';
import sparkles from '@iconify-icons/ion/sparkles';
import sparklesOutline from '@iconify-icons/ion/sparkles-outline';
import warning from '@iconify-icons/ion/warning';

export const ChevronDownIcon = (props: any) => <Icon icon={chevronDown} aria-hidden {...props} />;
export const HomeIcon = (props: any) => <Icon icon={home} aria-hidden {...props} />;
export const HomeOutlineIcon = (props: any) => <Icon icon={homeOutline} aria-hidden {...props} />;
export const InfoIcon = (props: any) => <Icon icon={informationCircle} aria-hidden {...props} />;
export const MenuIcon = (props: any) => <Icon icon={menu} aria-hidden {...props} />;
export const MenuOutline = (props: any) => <Icon icon={menuOutline} aria-hidden {...props} />;
export const NotificationOutline = (props: any) => <Icon icon={notificationsOutline} aria-hidden {...props} />;
export const PersonIcon = (props: any) => <Icon icon={person} aria-hidden {...props} />;
export const PersonOutlineIcon = (props: any) => <Icon icon={personOutline} aria-hidden {...props} />;
export const SearchIcon = (props: any) => <Icon icon={search} aria-hidden {...props} />;
export const SparklesIcon = (props: any) => <Icon icon={sparkles} aria-hidden {...props} />;
export const SparklesOutlineIcon = (props: any) => <Icon icon={sparklesOutline} aria-hidden {...props} />;
export const WarningIcon = (props: any) => <Icon icon={warning} aria-hidden {...props} />;
