import { Icon } from '@iconify-icon/solid';
import arrowDownCircle from '@iconify-icons/ion/arrow-down-circle';
import arrowDownCircleOutline from '@iconify-icons/ion/arrow-down-circle-outline';
import arrowUpCircle from '@iconify-icons/ion/arrow-up-circle';
import arrowUpCircleOutline from '@iconify-icons/ion/arrow-up-circle-outline';
import beakerFilled from '@iconify-icons/fluent/beaker-16-filled';
import beakerOutline from '@iconify-icons/fluent/beaker-16-regular';
import chevronDown from '@iconify-icons/ion/chevron-down';
import columnEditFilled from '@iconify-icons/fluent/column-edit-20-filled';
import columnEditOutline from '@iconify-icons/fluent/column-edit-20-regular';
import dismissFilled from '@iconify-icons/fluent/dismiss-12-filled';
import editFilled from '@iconify-icons/fluent/edit-16-filled';
import editOutline from '@iconify-icons/fluent/edit-16-regular';
import eye from '@iconify-icons/fluent/eye-12-filled';
import eyeOff from '@iconify-icons/fluent/eye-off-16-filled';
import filter from '@iconify-icons/fluent/filter-20-filled';
import filterAdd from '@iconify-icons/fluent/filter-add-20-filled';
import home from '@iconify-icons/ion/home';
import homeOutline from '@iconify-icons/ion/home-outline';
import informationCircle from '@iconify-icons/ion/information-circle';
import left from '@iconify-icons/fluent/arrow-left-12-filled';
import menu from '@iconify-icons/ion/menu';
import menuOutline from '@iconify-icons/ion/menu-outline';
import move from '@iconify-icons/fluent/arrow-move-20-filled';
import notificationsOutline from '@iconify-icons/ion/notifications-outline';
import person from '@iconify-icons/ion/person';
import personOutline from '@iconify-icons/ion/person-outline';
import presenceOffline10Regular from '@iconify-icons/fluent/presence-offline-10-regular';
import right from '@iconify-icons/fluent/arrow-right-12-filled';
import search from '@iconify-icons/ion/search';
import sortAsc from '@iconify-icons/fluent/text-sort-ascending-16-regular';
import sortDesc from '@iconify-icons/fluent/text-sort-descending-16-regular';
import sparkles from '@iconify-icons/ion/sparkles';
import sparklesOutline from '@iconify-icons/ion/sparkles-outline';
import warning from '@iconify-icons/ion/warning';

export const ArrowDownCircleIcon = (props: any) => <Icon icon={arrowDownCircle} aria-hidden {...props} />;
export const ArrowDownCircleOutlineIcon = (props: any) => <Icon icon={arrowDownCircleOutline} aria-hidden {...props} />;
export const ArrowUpCircleIcon = (props: any) => <Icon icon={arrowUpCircle} aria-hidden {...props} />;
export const ArrowUpCircleOutlineIcon = (props: any) => <Icon icon={arrowUpCircleOutline} aria-hidden {...props} />;
export const BeakerFilledIcon = (props: any) => <Icon icon={beakerFilled} aria-hidden {...props} />;
export const BeakerOutlineIcon = (props: any) => <Icon icon={beakerOutline} aria-hidden {...props} />;
export const ChevronDownIcon = (props: any) => <Icon icon={chevronDown} aria-hidden {...props} />;
export const ColumnEditFilledIcon = (props: any) => <Icon icon={columnEditFilled} aria-hidden {...props} />;
export const ColumnEditOutlineIcon = (props: any) => <Icon icon={columnEditOutline} aria-hidden {...props} />;
export const DismissIcon = (props: any) => <Icon icon={dismissFilled} aria-hidden {...props} />;
export const EditFilledIcon = (props: any) => <Icon icon={editFilled} aria-hidden {...props} />;
export const EditOutlineIcon = (props: any) => <Icon icon={editOutline} aria-hidden {...props} />;
export const EyeIcon = (props: any) => <Icon icon={eye} aria-hidden {...props} />;
export const EyeOffIcon = (props: any) => <Icon icon={eyeOff} aria-hidden {...props} />;
export const FilterAddIcon = (props: any) => <Icon icon={filterAdd} aria-hidden {...props} />;
export const FilterIcon = (props: any) => <Icon icon={filter} aria-hidden {...props} />;
export const HomeIcon = (props: any) => <Icon icon={home} aria-hidden {...props} />;
export const HomeOutlineIcon = (props: any) => <Icon icon={homeOutline} aria-hidden {...props} />;
export const InfoIcon = (props: any) => <Icon icon={informationCircle} aria-hidden {...props} />;
export const LeftIcon = (props: any) => <Icon icon={left} aria-hidden {...props} />;
export const MenuIcon = (props: any) => <Icon icon={menu} aria-hidden {...props} />;
export const MenuOutline = (props: any) => <Icon icon={menuOutline} aria-hidden {...props} />;
export const MoveIcon = (props: any) => <Icon icon={move} aria-hidden {...props} />;
export const NotificationOutline = (props: any) => <Icon icon={notificationsOutline} aria-hidden {...props} />;
export const OffIcon = (props: any) => <Icon icon={presenceOffline10Regular} aria-hidden {...props} />;
export const PersonIcon = (props: any) => <Icon icon={person} aria-hidden {...props} />;
export const PersonOutlineIcon = (props: any) => <Icon icon={personOutline} aria-hidden {...props} />;
export const RightIcon = (props: any) => <Icon icon={right} aria-hidden {...props} />;
export const SearchIcon = (props: any) => <Icon icon={search} aria-hidden {...props} />;
export const SortAscIcon = (props: any) => <Icon icon={sortAsc} aria-hidden {...props} />;
export const SortDescIcon = (props: any) => <Icon icon={sortDesc} aria-hidden {...props} />;
export const SparklesIcon = (props: any) => <Icon icon={sparkles} aria-hidden {...props} />;
export const SparklesOutlineIcon = (props: any) => <Icon icon={sparklesOutline} aria-hidden {...props} />;
export const WarningIcon = (props: any) => <Icon icon={warning} aria-hidden {...props} />;