-- Role: dataprotection_owner
-- DROP ROLE IF EXISTS dataprotection_owner;

CREATE ROLE dataprotection_owner WITH
  NOLOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

-- Role: dataprotection_manager
-- DROP ROLE IF EXISTS dataprotection_manager;

CREATE ROLE dataprotection_manager WITH
  LOGIN
  NOSUPERUSER
  NOINHERIT
  NOCREATEDB
  NOCREATEROLE
  NOREPLICATION;

-- Database: dataprotection
-- DROP DATABASE IF EXISTS dataprotection;

CREATE DATABASE dataprotection
    WITH
    OWNER = dataprotection_owner
    ENCODING = 'UTF8'
    LC_COLLATE = 'English_United States.1252'
    LC_CTYPE = 'English_United States.1252'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;

GRANT ALL ON DATABASE dataprotection TO dataprotection_owner;
GRANT ALL ON DATABASE dataprotection TO pg_database_owner;
GRANT TEMPORARY, CONNECT ON DATABASE dataprotection TO dataprotection_manager;
REVOKE ALL ON DATABASE dataprotection FROM PUBLIC;

-- CONNECT TO DATABASE

SET ROLE dataprotection_owner;

DROP SCHEMA IF EXISTS public;

SET ROLE pg_database_owner;

-- SCHEMA: dp
-- DROP SCHEMA IF EXISTS dp ;

CREATE SCHEMA IF NOT EXISTS dp
    AUTHORIZATION pg_database_owner;

GRANT USAGE ON SCHEMA dp TO dataprotection_manager;
GRANT ALL ON SCHEMA dp TO pg_database_owner;

-- Table: dp.data_protection_keys
-- DROP TABLE IF EXISTS dp.data_protection_keys;

CREATE TABLE IF NOT EXISTS dp.data_protection_keys
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    friendly_name text COLLATE pg_catalog."default",
    xml text COLLATE pg_catalog."default",
    CONSTRAINT pk_data_protection_keys PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS dp.data_protection_keys
    OWNER to pg_database_owner;

GRANT DELETE, INSERT, SELECT, UPDATE ON TABLE dp.data_protection_keys TO dataprotection_manager;
GRANT ALL ON TABLE dp.data_protection_keys TO pg_database_owner;
