// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface Organization {
    organizationId: string;
    name: string;
    databaseName: string;
    dbOwnerRole: string;
    created: Date;
}