import { Organization } from "./Cluster.Directory.Models";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface CreateOrganizationInput {
    name: string;
    databaseName: string;
}

export interface CreateOrganizationResult {
    organizationId: string;
}

export interface CreateOrganizationRoleInput {
    organizationId: string;
    roleName: string;
    memberDbRoles: string[];
}

export interface FetchOrganizationsOutput {
    organizations: Organization[];
}

export interface QueryDirectoryInput {
    sql: string;
}