import { Column, TableIndex } from "./DatabaseDefinition.Models";

// DO NOT MODIFY BELOW THIS LINE
// Generated by GiantTeam.Tools

export interface AlterColumn extends DatabaseAlteration {
    $type: 'AlterColumn';
    schemaName: string;
    tableName: string;
    column: Column;
    modifications: AlterColumnModification[];
}

export enum AlterColumnModification {
    Nullability = 0,
    Default = 1,
    Type = 2,
    Generated = 3,
}

export interface AlterIndex extends DatabaseAlteration {
    $type: 'AlterIndex';
    schemaName: string;
    tableName: string;
    index: TableIndex;
}

export interface ChangeTableOwner extends DatabaseAlteration {
    $type: 'ChangeTableOwner';
    schemaName: string;
    tableName: string;
    newOwner: string;
}

export interface CreateColumn extends DatabaseAlteration {
    $type: 'CreateColumn';
    schemaName: string;
    tableName: string;
    column: Column;
}

export interface CreateIndex extends DatabaseAlteration {
    $type: 'CreateIndex';
    schemaName: string;
    tableName: string;
    index: TableIndex;
}

export interface CreateSchema extends DatabaseAlteration {
    $type: 'CreateSchema';
    schemaName: string;
}

export interface CreateTable extends DatabaseAlteration {
    $type: 'CreateTable';
    schemaName: string;
    tableName: string;
    columns: Column[];
}

export interface DatabaseAlteration {
    $type: string;
}

export interface DropColumn extends DatabaseAlteration {
    $type: 'DropColumn';
    schemaName: string;
    tableName: string;
    columnName: string;
}

export interface DropIndex extends DatabaseAlteration {
    $type: 'DropIndex';
    schemaName: string;
    tableName: string;
    index: TableIndex;
}

export interface RenameColumn extends DatabaseAlteration {
    $type: 'RenameColumn';
    schemaName: string;
    tableName: string;
    columnName: string;
    newColumnName: string;
}

export interface RenameTable extends DatabaseAlteration {
    $type: 'RenameTable';
    schemaName: string;
    tableName: string;
    newTableName: string;
}