// DO NOT MODIFY!
// Generated by GiantTeam.Tools

export interface LoginInput {
    username?: string;
    password?: string;
    remainLoggedIn: boolean;
}

export interface LoginOutput {
    status: LoginStatus;
    message?: string;
}

export enum LoginStatus {
    Authenticated = 200,
    InvalidInput = 400,
}

export interface RegisterInput {
    name: string;
    email: string;
    username: string;
    password: string;
    passwordConfirmation: string;
}

export interface RegisterOutput {
    status: RegisterStatus;
    message?: string;
}

export enum RegisterStatus {
    Success = 200,
    Error = 400,
}