version: "3.8"
services:

  db:
    image: postgres:15.1
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/POSTGRES_PASSWORD_FILE
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      mode: global
    secrets:
      - POSTGRES_PASSWORD_FILE

volumes:
  db-data:


secrets:
  POSTGRES_PASSWORD_FILE:
    file: ./POSTGRES_PASSWORD_FILE
