# Docker Compose
# https://docs.docker.com/compose/compose-file/#env_file
# https://docs.docker.com/compose/compose-file/deploy/

version: "3.8"

services:
  db:
    image: localhost:5000/giantteam:latest
    ports:
      - "80:80"
    #      - "8443:443"
    env_file: settings.env
    secrets:
      - DataProtectionCertificate
      - DataProtectionConnection__Password
      - MigratorConnection__Password
      - MgmtConnection__Password
      - SecConnection__Password
    deploy:
      mode: global

secrets:
  DataProtectionCertificate:
    file: ./DataProtectionCertificate
  DataProtectionConnection__Password:
    file: ./DataProtectionConnection__Password
  MigratorConnection__Password:
    file: ./MigratorConnection__Password
  MgmtConnection__Password:
    file: ./MgmtConnection__Password
  SecConnection__Password:
    file: ./SecConnection__Password
